name: Move new issues into Done
on:
  pull_request:
    branches:
      - master
    types:
      - closed

jobs:
  connect:
    runs-on: ubuntu-latest
    steps:
      - name: When pull_request is closed, move the connected issue to the Done column
        uses: wktk/github-project-connect-action@v1
        with:
          github-token: ${{ secrets.GHPROJECT_TOKEN }}
          column-url: https://github.com/raihara3/kanban-action/projects/1#column-15366624 # column url
