name: Move new issues into In review
on:
  pull_request_target:
    types:
      - opened
jobs:
  move-assigned-card:
    runs-on: ubuntu-latest
    steps:
      - uses: alex-page/github-project-automation-plus@v0.3.0
        with:
          project: test
          column: In review
          repo-token: ${{ secrets.GHPROJECT_TOKEN }}
