name: Move new issues into In review
on:
  pull_request:
    types:
      - review_requested

jobs:
  connect:
    runs-on: ubuntu-latest
    steps:
      - name: When pull_request is review_requested, move the connected issue to the Reviewing column
        uses: wktk/github-project-connect-action@v1
        with:
          github-token: ${{ secrets.GHPROJECT_TOKEN }}
          column-url: https://github.com/raihara3/kanban-action/projects/1#column-15366622 # column url
